### ISSUE TITLE
sending message fails with 'empty device list' error

### ISSUE THREAD

**Issue by diracdeltas** [diracdeltas/signal-muon#2]
when i try to send a message, it shows up as unsent and the debug log shows something like:
```
2017-03-06T08:05:02.072Z GET https://textsecure-service-staging.whispersystems.org:80/v2/keys/+[REDACTED]/1
2017-03-06T08:05:02.938Z GET https://textsecure-service-staging.whispersystems.org:80/v2/keys/+[REDACTED]/1 200 Success
2017-03-06T08:05:03.129Z PUT https://textsecure-service-staging.whispersystems.org:80/v1/messages/+[REDACTED]
2017-03-06T08:05:03.233Z PUT https://textsecure-service-staging.whispersystems.org:80/v1/messages/+[REDACTED]911 409 Error
2017-03-06T08:05:03.235Z deleting session for  +[REDACTED].1
2017-03-06T08:05:03.249Z OutgoingMessageError
2017-03-06T08:05:03.249Z Got empty device list when loading device keys Error
    at chrome-extension://iopnjipkpnmbpjaalcjcpcbfcnjknmmo/js/libtextsecure.js:30:33
    at chrome-extension://iopnjipkpnmbpjaalcjcpcbfcnjknmmo/js/libtextsecure.js:136:3
    at chrome-extension://iopnjipkpnmbpjaalcjcpcbfcnjknmmo/js/libtextsecure.js:39653:3
```

**Comment by diracdeltas** [comment]
ah, i think this only happens when i try to send a message to numbers not registered on the staging server. when i send messages between Signal-Muon accounts, it seems to work fine.

for some reason, it doesn't work when I send a message to myself though.
